
package projetoed;


import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class PainelListaDE extends javax.swing.JDialog {

    public PainelListaDE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDE1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        BotaoInsere = new javax.swing.JButton();
        BotaoRemove = new javax.swing.JButton();
        posicao = new javax.swing.JTextField();
        TextoInput = new javax.swing.JTextField();
        TextoPesquisa = new javax.swing.JTextField();
        PesquisaPos = new javax.swing.JButton();
        PesquisaVal = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(51, 51, 255));

        ListaDE1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ListaDE1.setName("ListaDE1"); // NOI18N
        ListaDE1.setVisibleRowCount(1);
        jScrollPane2.setViewportView(ListaDE1);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Lista Duplamente Encadeada");

        BotaoInsere.setText("Inserir");
        BotaoInsere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoInsereActionPerformed(evt);
            }
        });

        BotaoRemove.setText("Remover");
        BotaoRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoveActionPerformed(evt);
            }
        });

        posicao.setText("1");

        TextoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoInputActionPerformed(evt);
            }
        });

        PesquisaPos.setText("Pesquisar por Posição");
        PesquisaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaPosActionPerformed(evt);
            }
        });

        PesquisaVal.setText("Pesquisar por valor");
        PesquisaVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posicao)
                            .addComponent(TextoInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(BotaoInsere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(PesquisaVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PesquisaPos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(TextoPesquisa, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoInsere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoRemove)
                    .addComponent(posicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(TextoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PesquisaPos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PesquisaVal)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoInsereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoInsereActionPerformed
        // TODO add your handling code here:
//        Fila1.setModel(modelo);
//        modelo.addElement(TextoInput.getText());
          
          
          int valor = Integer.parseInt(TextoInput.getText());
          int pos = Integer.parseInt(posicao.getText());
          L1de.insere(pos,valor);
          UpdateList();
          TextoInput.setText("");
          
    }//GEN-LAST:event_BotaoInsereActionPerformed

    private void BotaoRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoveActionPerformed
        // TODO add your handling code here:
        
        int pos = Integer.parseInt(posicao.getText());
        L1de.remove(pos);
        UpdateList();
    }//GEN-LAST:event_BotaoRemoveActionPerformed

    private void TextoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoInputActionPerformed

    private void PesquisaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaPosActionPerformed
        // TODO add your handling code here:
        String texto = TextoPesquisa.getText();
        int a = Integer.parseInt(texto);
        int resultado = L1de.PesquisaValor(a);
        JOptionPane.showMessageDialog(this, "Na posição " + a + " temos o elemento " + resultado);
        
    }//GEN-LAST:event_PesquisaPosActionPerformed

    private void PesquisaValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaValActionPerformed
        // TODO add your handling code here:
        String texto = TextoPesquisa.getText();
        int a = Integer.parseInt(texto);
        int resultado = L1de.Pesquisaposicao(a);
        JOptionPane.showMessageDialog(this, "O Elemento " + a + " está na posição " + resultado);
    }//GEN-LAST:event_PesquisaValActionPerformed

    private void UpdateList(){
        
        modelo = new DefaultListModel();
        ListaDE1.setModel(modelo);
        LDE.No n;
        n = L1de.inicio;
        
        for (int i=0; i< L1de.tamanho(); i++){
            modelo.addElement(n.getConteudo());
            n = n.getProx();
        
        }
            
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PainelFila dialog = new PainelFila(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoInsere;
    private javax.swing.JButton BotaoRemove;
    private javax.swing.JList<String> ListaDE1;
    private javax.swing.JButton PesquisaPos;
    private javax.swing.JButton PesquisaVal;
    private javax.swing.JTextField TextoInput;
    private javax.swing.JTextField TextoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField posicao;
    // End of variables declaration//GEN-END:variables
    DefaultListModel modelo = new DefaultListModel();
    LDE L1de = new LDE();
    
}


